#!/bin/bash
echo "Atualizando repositórios"
sudo apt update -y && apt upgrade -y
echo "Adicionando repositório do PHP via ppa"
sudo add-apt-repository ppa:ondrej/php -y
echo "Atualizando repositórios"
sudo apt update -y
echo "Instalando PHP8.2"
sudo apt install php8.2 libapache2-mod-php8.2 php8.2-cli php8.2-common php8.2-fpm php8.2-mysql php8.2-zip php8.2-gd php8.2-mbstring php8.2-curl php8.2-xml php8.2-bcmath php8.2-gettext php8.2-cgi php8.2-fpm -y
echo "Vendo versão do php instalado"
php --version